### ISSUE TITLE
Dropbox public download links for version 5 overloaded

### ISSUE THREAD

**Issue by terabyte128** [infernoboy/JavaScript-Blocker#34]
Possible to host releases with GitHub instead?

**Comment by infernoboy** [comment]
The download links shouldn't be going to Dropbox anymore. Where are you trying to download it from?

**Comment by terabyte128** [comment]
The download link here: http://javascript-blocker.toggleable.com/

**Comment by infernoboy** [comment]
The one link I forgot to update… thanks for letting me know; it's fixed now.

**Comment by m-urban** [comment]
The link from the page mentioned is still broken for some reason…
http://lion.toggleable.com:160/jsblocker/download/JSB5.safariextz

**Comment by infernoboy** [comment]
Dropbox has unbanned the links. Please make sure your router/firewall are not blocking outgoing connections to port 160

**Comment by m-urban** [comment]
Tried it from outside the corporate environment today and it worked, thanks!
